name: Rust

on:
  push:
    branches: [ rewrite, rewrite-feature/** ]
  pull_request:
    branches: [ rewrite, rewrite-feature/** ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
